### ISSUE TITLE
tasmocompiler

### ISSUE THREAD

**Issue by Dunkelschunkel** [jdeath/homeassistant-addons#11]
hi @jdeath, 

using hassOS on raspberry i am no longer able to install ttasmocompiler. You are pulling x86 and not latest. ist this on purpose?

Cheers Dunkelschunkel

**Comment by jdeath** [comment]
No reason , just bad practices on my part. I don’t use it anymore. I can try to update the image it pulls but will take me a couple days. You can download the repo, copy the tasmocompiler directory to your \\homeassistant\addons directory. You can change the docket image it pulls on one of the files. It should show up in the addonstore under local addons. Please do a PR to the repo if you get to it before me.

**Comment by Dunkelschunkel** [comment]
@jdeath hi there,

thanks for taking the time to answer. I tried to do a pull request. Having no proper experience using github as a tool myself I hope everything works out well.

Cheers Dunkelschunkel
