### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ViPeR5000** [jdeath/homeassistant-addons#13]
Can't install benzino77/tasmocompiler:10.4.1: 404 Client Error for http+docker://localhost/v1.42/images/create?tag=10.4.1&fromImage=benzino77%2Ftasmocompiler&platform=linux%2Famd64: Not Found ("manifest for benzino77/tasmocompiler:10.4.1 not found: manifest unknown: manifest unknown")

**Comment by jdeath** [comment]
Argh. I'll play with it. I made the change due to other people having issues. I didn;t test

**Comment by jdeath** [comment]
Ok. Should be fixed now. Re-open if not.
