### ISSUE TITLE
typedrawtype can't be uninstalled

### ISSUE THREAD

**Issue by googanhiem** [jdeath/homeassistant-addons#14]
I have this issue were typedrawtype never worked and now can't be uninstalled. I've tried the gui, cli and portainer to remove it.

```
ha ad uninstall 2effc9b9_typedrawtype

Error: Can't remove image bronkoknorb/type-draw-type-game: 400 Client Error for http+docker://localhost/v1.42/images/bronkoknorb/type-draw-type-game:?force=True&noprune=False: Bad Request ("invalid reference format")
```

Think the install is borked and thats causing it to do enough to make it think its installed, but without actually doing anything. when you install it, all it does is this in about 3 seconds

```
23-08-02 23:58:46 INFO (MainThread) [supervisor.addons] Creating Home Assistant add-on data folder /data/addons/data/local_typedrawtype
23-08-02 23:58:46 INFO (SyncWorker_6) [supervisor.docker.interface] Downloading docker image bronkoknorb/type-draw-type-game with tag .
```

**Comment by jdeath** [comment]
I am seeing the same thing. It used to work, perhaps the image changed. I'll take a look and take down if I cannot fix. I also cannot seem to remove it....

**Comment by jdeath** [comment]
I think I fixed it. Try it.
1. From terminal do a "docker pull bronkoknorb/type-draw-type-game" , this will pull a fresh image
2. Refresh the addons and update to latest version of addon. The UI started for me going to the port. didn't actually play it

**Comment by googanhiem** [comment]
Updating and uninstalling worked, didn't need to go and docker pull. You're a legend!

**Comment by jdeath** [comment]
Glad it worked. Docker pull was a hunch because it was erroring that the image did not exist. Many of these addons I don't actually use, so often things break.
