### ISSUE TITLE
MeTube - Configurable environment variables

### ISSUE THREAD

**Issue by dokatomi** [jdeath/homeassistant-addons#21]
Hi,

It would be nice if at least the DELETE_FILE_ON_TRASHCAN environment variable will be configurable.
Now if I use only the gui for downloading (and downloading the downloaded file), then deleting through the gui all the files remain in the HA storage.
I want to delete the file if I push the trashcan.

Thanks

**Comment by jdeath** [comment]
I'll see if I can add it. It would be a change to the setup to add that, but I have done similar things before

**Comment by jdeath** [comment]
If you uninstall the addon, refresh the addon store, and reinstall the addon, it should not have a switch to set the trashcan variable. It defaults to off. I did not test it. I can probably add more variables in the future.

**Comment by dokatomi** [comment]
Tested, working as expected :)
Thank you.
