### ISSUE TITLE
Unable to install / update wgeasy

### ISSUE THREAD

**Issue by EggEek-net** [jdeath/homeassistant-addons#22]
Hi ! 

When I try to install or update wgeasy I get this error message :

` invalid tag '2effc9b9/amd64-addon-wgeasy:': invalid reference format `

I think that the "upstream_version" variable in the updater.json file is missing, but I'm not sure.

Could you please have a look to this, wgeasy is such a great integration to HA ? Thanks a lot for your work by the way !

**Comment by jdeath** [comment]
Yes, I got that too and that was the issue. My auto update script seemed to mess up for some reason. Should be fixed now.
