### ISSUE TITLE
SHIORI - armv7 not supported

### ISSUE THREAD

**Issue by amarok77** [jdeath/homeassistant-addons#25]
why you not add support for armv7?
shiori support it...

**Comment by jdeath** [comment]
Fixed (I think). Need to refresh addon store.

You can always download an addon into your /addons directory, and make the change yourself. If it works, do a PR.

**Comment by amarok77** [comment]
i tried to make my own shiori addon.... but it doesn't work.... your take me the same error:

Impossibile installare il componente aggiuntivo
Can't install ghcr.io/go-shiori/shiori:1.6.1: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=1.6.1&fromImage=ghcr.io%2Fgo-shiori%2Fshiori&platform=linux%2Farm%2Fv7: Internal Server Error ("manifest unknown")

**Comment by jdeath** [comment]
I get the same error on X86. They must have changed something. I have not used it in a while. I will look into it.

**Comment by jdeath** [comment]
exit fixed
