### ISSUE TITLE
Earthwalker install issue

### ISSUE THREAD

**Issue by marcetad** [jdeath/homeassistant-addons#26]
Trying to install Earthwalker.

I get the following error.

### Failed to install add-on
 Can't install registry.gitlab.com/glatteis/earthwalker:1: 404 Client Error for http+docker://localhost/v1.44/images/create?tag=1&fromImage=registry.gitlab.com%2Fglatteis%2Fearthwalker&platform=linux%2Famd64: Not Found ("manifest for registry.gitlab.com/glatteis/earthwalker:1 not found: manifest unknown: manifest unknown") 

Could you please help?

**Comment by jdeath** [comment]
Looks like the docker image the addon used was taken down. I will try to fork the code and see if I could build my own.

**Comment by jdeath** [comment]
Should be fixed now. They changed the versioning method. Check for add on updates and then it should install
