### ISSUE TITLE
update to version 13 cause connection to all client to stop working 

### ISSUE THREAD

**Issue by Shiroe93** [jdeath/homeassistant-addons#28]
after updating to version 12 to 13 i'm unable to connect to my wiregard server even if a new client is created   
no error in logs
the problem goes away if i rollback to 12

**Comment by jdeath** [comment]
No problem here.
Check this issue: https://github.com/jdeath/homeassistant-addons/issues/24

An error caused a "12" being put as the default in WG_POST_UP: WG_POST_DOWN:, PASSWORD . Check that this was not added to your version 13 config.....

**Comment by Shiroe93** [comment]
I checked and nothing has been added to my config

**Comment by Shiroe93** [comment]
found the problem in the[ issue ](https://github.com/wg-easy/wg-easy/issues/1032)tracker of the wgeasy repo you used for this add on it's marked as solved so i will stay on 12 while i wait for an update

**Comment by jdeath** [comment]
Weird. Can you not use the default port? Anyways, once they push a new version, I'll update the addon.

**Comment by Shiroe93** [comment]
No problem from what i can see it's not like version 12 has some major security flaws that needs to be fixed asap 
To answer your question If revert back to the original port i will have to change the client config too and some might be challenging so i will wait

**Comment by Shiroe93** [comment]
fixed https://github.com/jdeath/homeassistant-addons/issues/29#issuecomment-2282199272
