### ISSUE TITLE
Port redirection is not applied in the configuration generated by the UI

### ISSUE THREAD

**Issue by adriy-be** [jdeath/homeassistant-addons#29]
When I change the port redirection in HA, the UI don't take the new port into account.
We can change ``WG_PORT``, but there is a mismatch with the HA configured port.

The env variable ``WG_PORT`` should not be accessible.
The future env variable ``WG_CONFIG_PORT`` must be accessible to have a correct configuration in the UI.
Follow :
https://github.com/wg-easy/wg-easy/pull/1080

**Comment by jdeath** [comment]
Duplicate of #28 

Once a fix is in v14, I will make the change in the addon. For now, roll back to v12 which works correctly with a changed port.

**Comment by adriy-be** [comment]
@jdeath not sure if that is the same topic. If we change the WG_PORT, there is a mismatch with the HA add-on configuration ``config.json`` who as fixed port, if the port change inside the container there is a mismatch.
I'm currently run the last version with port redirection configured in HA not with the env variable of the container, that work but I need to manually change the port in my config of WireGuard.

**Comment by jdeath** [comment]
IF you change WG_PORT, can't you also change the port exposed too? In the network configuration section, you can change the udp port. I assume they both need to match.

I guess let me know exactly what you think should change or do a PR and I can review.

**Comment by adriy-be** [comment]
In my knowledge, you can't change WG_PORT due to this port is fixed in config.json, but you can forward the port in the network part of the add-on.

I'm waiting the next version of wg-easy to do a PR.
There is the PR about my change in wg-easy : https://github.com/wg-easy/wg-easy/pull/1090
There is your repo with the development container of wg-easy : https://github.com/adriy-be/homeassistant-addons-jdeath/tree/main/wgeasy

So, I'm a beginner with HA add-on, don't hesitate to comment If I do a mistake or if there is a better way to do that.

**Comment by jdeath** [comment]
??? Just above the screen shot you posted, you can change the change WG_PORT in the CONFIGURATION section. It is the 4th entry down. You need to have it match the port you set in the network tab. It will override the port set in config.json

I am told you need version 12 of the addon, because version 13 of upstream wgeasy has an issue that it does not set the port correctly.

**Comment by adriy-be** [comment]
That not correct
51820 is fixed in config.json and is the internal container port, the internal container port is WG_PORT and due to it's fixed by the config.json it must not change.
63934 is the exposed port who is remapped to the internal container port (51820)


WWW<---Router--->Exposed Port<---Container--->Internal port
![image](https://github.com/jdeath/homeassistant-addons/assets/9422221/5bd15983-95cd-4269-82ff-7fb4430804ae)


Try this : https://github.com/adriy-be/homeassistant-addons-jdeath/tree/main/wgeasy
You could see if you change WG_CONFIG_PORT and change the exposed port in HA, that working fine.


The WG_EASY PR is complete, I do the change current of this week
https://github.com/wg-easy/wg-easy/pull/1090


There is my full config with comments
![image](https://github.com/jdeath/homeassistant-addons/assets/9422221/37ffa38a-d219-4324-b686-ae00c9d36edc)

**Comment by jdeath** [comment]
This must be a change in WGEASY v13, because it worked fine changing WG_PORT in earlier versions then making the exposed udp port match. The run.sh updates the environmental variable.

If WG_PORT should not be changed anymore, then remove it from the variables exposed in config.json and run.sh when you do a PR. Also, please update the readme so it is clear what to change. Better yet, just have WG_PORT in the homeassistant config just updated WG_PORT_CONFIG environmental variable. Then a user does not have to change anything. I'll reopen until PR complete

**Comment by Shiroe93** [comment]
> There is my full config with comments
> ![image](https://private-user-images.githubusercontent.com/9422221/338125163-37ffa38a-d219-4324-b686-ae00c9d36edc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzMDY2NjcsIm5iZiI6MTcyMzMwNjM2NywicGF0aCI6Ii85NDIyMjIxLzMzODEyNTE2My0zN2ZmYTM4YS1kMjE5LTQzMjQtYjY4Ni1hZTAwYzlkMzZlZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTBUMTYxMjQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjA3YTA5Y2ZjMzBlNjlmYzI4YzRkMjI4NzMxOGYxYjY3ZjQzMDAzNjdhZjU4OWIyMzVkNjVlZGY1MjNhODJmMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ClWtrLUKASfAKc0lz4K-oxDkIJsDmsGzCh1VFWeYyzM)

this has fixed the issue for me in v14

**Comment by Shiroe93** [comment]
![Screenshot_20240810_193452_Firefox.jpg](https://github.com/user-attachments/assets/bb09ace5-788a-46d0-8dea-109a00f7db84)

**Comment by adriy-be** [comment]
@jdeath thanks for the update. The port is correctly configured in the config.
![image](https://github.com/user-attachments/assets/a2dfcc06-e885-4c95-96a9-d7dbdeba1e65)
