### ISSUE TITLE
[Suggestion!] Custom Save Path

### ISSUE THREAD

**Issue by SiriosDev** [jdeath/homeassistant-addons#3]
Adding the Save Path field, in the Add-On options or directly in the web UI

**Comment by jdeath** [comment]
For what addon?

**Comment by SiriosDev** [comment]
I am dumb, sorry, I was referring to metube.

**Comment by jdeath** [comment]
Ok. I'll look into it. Changing it would rearchitect how the docker image is called from homeassistant. Also, only /share /config/ /ssl can be written from homeassistant so the options are limited.
