### ISSUE TITLE
possibility of changing environment variables in flatnote

### ISSUE THREAD

**Issue by matiasmoralesm** [jdeath/homeassistant-addons#30]
Hello, I have been trying to change the development variables of the addon “Flatnotes” for a couple of days and I have not succeeded.
I need to be able to change :
“FLATNOTES_AUTH_TYPE”.
“FLATNOTES_PASSWORD=changeMe!”

For more security when entering my notes.

In the webui configuration only the port appears as configurable

**Comment by jdeath** [comment]
This docker will not allow me to add jq, so I do not know how to do this.

You can easily download this repo's code, copy the entire flatnotes folder into \\homeassistant\addons\

If you refresh your addon store, you will see a local copy of flatnotes . Then go into config.json and make any change you wish. Refresh addon store and install.

**Comment by jdeath** [comment]
Completed with commit #a4fc127 . Uninstall and reinstall the addon. Not tested, but should work
