### ISSUE TITLE
Earthwalker - Exec format error

### ISSUE THREAD

**Issue by twerff** [jdeath/homeassistant-addons#37]
Trying to run Earthwalker on an rpi4-64 with HA supervised 2024.6.4

# Expected behavior
I would expect the terminal addon to run the same way it did before the update, with the same config.

# Actual behavior
The addon will not start anymore and reports the error: `[FATAL tini (7)] exec /init failed: Exec format error`.
Uninstalling the addon and re-installing it, results in the same error.

# Steps to reproduce
Install hassio supervised on a raspberry pi. Install the Earthwalker add-on from this repo. Start the add-on and observe the log.

**Comment by jdeath** [comment]
This relies on the image published by the author. I can only test on x86 and works fine with a fresh install. The upstream author may no longer be making the correct aarch64 image. If I have time, I can see if can rebuild the image from source.

**Comment by twerff** [comment]
Thanks for replying! I expected as much. I saw a similar issue posted on the original repo, the reporter was able to build the image for their own platform to fix it. I am, however, not so gifted

**Comment by jdeath** [comment]
[earthwalker.zip](https://github.com/user-attachments/files/16202051/earthwalker.zip)

If you exact the earthwalker directory into /addons/ , then go to Addon Store, a version should show up in your local addons (might need to Check for Updatetes, then refresh browser). This will compile it locally.

**Comment by twerff** [comment]
It works like a charm! Thanks

**Comment by jdeath** [comment]
Cool. Perhaps I'll post a version that works this way.
