### ISSUE TITLE
[EmulatorJS] Issues with frontend

### ISSUE THREAD

**Issue by hulkhaugen** [jdeath/homeassistant-addons#4]
I've been fiddeling with the EmulatorJS, but I've managed to get it somehow working after changing the permissions for the `/share/emulatorjs` folder. The "issue" I have now is that nothing comes up when i go to the frontend port 80 (Port 8988 in my case), I just get a pop-up saying `No items to load, please add some games`. However, If i go to `http://192.168.1.3:3088//frontend/index.html` (The 3000 port), it comes up with all the games as it should be, so the setup should be corret. For local play, that's ok, but I want to expose the frontend port without opening access to the backend port.

**Comment by jdeath** [comment]
I haven't used in a long time. Seems they changed something. I'll look into it.

**Comment by jdeath** [comment]
Try uninstalling the addon, then reinstall it. I made changes
You now need to make 2 directories `/share/emulatorjs/config` and `/share/emulatorjs/data`
Now add your games in the directories, scan for them in the admin, follow step 1 and step 2 to add them to config. They should now be playable in the non admin port

**Comment by hulkhaugen** [comment]
Cheers, seems like that did the trick :D
