### ISSUE TITLE
Trilium Next Arm

### ISSUE THREAD

**Issue by MrAyianaLex** [jdeath/homeassistant-addons#40]
Hello,
Would it be possible to add compatibility with ARM processors in the configuration because it was added with version 0.90.4
https://github.com/TriliumNext/Notes/releases/tag/v0.90.4
Thank

**Comment by jdeath** [comment]
Refresh the addon store. Hopefully should work.

**Comment by MrAyianaLex** [comment]
Hello,
It's work
