### ISSUE TITLE
wg-easy is not working since v14 

### ISSUE THREAD

**Issue by jakwarrior** [jdeath/homeassistant-addons#43]
When starting the addon, there is the following error: 
```
/app/lib/Server.js:311
throw new Error('DO NOT USE PASSWORD ENVIRONMENT VARIABLE. USE PASSWORD_HASH INSTEAD.
See https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md');
```
There is a breaking change in wg-easy v14:
https://github.com/wg-easy/wg-easy/releases

> Major changes
PASSWORD has been replaced by PASSWORD_HASH

**Comment by jdeath** [comment]
It should work now. Reload addon store and then rebuild addon. Tested with and without setting PASSWORD_HASH. Added into in readme to set password, if you want to use it.

I would not expose this directly to the internet.  It does work via ingress, so I would stick with that!
