### ISSUE TITLE
METUBE Download directory

### ISSUE THREAD

**Issue by trackerr** [jdeath/homeassistant-addons#49]
Could you add an option to METUBE for a custom download directory setting in homeassistant addon config?
I would love to see this option available since I use a different folder for storing files.

**Comment by jdeath** [comment]
I'll try to add it in the next week or so. 

You can download the code from this repo, move the metube folder into addons and change the value to wherever you like. Could also add the option yourself and do a PR. Should be straight forward to follow what I did for the trashcan option.

**Comment by jdeath** [comment]
Can be changed to anything in share
